<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <Target Name="CustomCopy" AfterTargets="Build">
    <ItemGroup>
      <MyFiles Include="DefaultItems\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(MyFiles)" DestinationFolder="$(OutDir)\DefaultItems\%(RecursiveDir)" />
  </Target>

</Project>